### ISSUE TITLE
TODO list for Hotel data specification 

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hotel-schemas#4]
**This is a list of things we know that are missing or imperfect in our hotel data specification. This list is not ordered by priority.**

Our goal is to make a list of every missing piece in this meta issue and deal with every single thing when the time is right. So, if you are missing something in our data format, please leave a comment here, we will add it to our TODO list. If you would like to help us with something, create a separate issue for a single task and leave us a comment here. All the related discussion should then happen in that separate issue.

Thank you for your contributions!

---

# TODO list

- [x] ~~descriptions - add business registration number to hotel object or some global identifier (#87)~~
- [ ] descriptions - add support for hotel group or hotel chain
- [x] ~~inventory, descriptions - improve amenities enumeration (and consider pricing of amenities) (#88)~~
- [x] ~~descriptions - add categories (such as romantic, business...) (#85, #86)~~
- [ ] descriptions - improve room properties (#98)
- [ ] descriptions - Optional paid services available on-site (bike rental etc.) (See also https://github.com/windingtree/wt-hackathon/pull/18, #96) + booking protocol needs to take this into account
- [ ] pricing - refine restrictions (arrival, departure, applicable days...)
- [ ] pricing - different cancellation policies for different rate plans
- [x] ~~pricing - cancellation terms~~
- [ ] descriptions - internationalization support (See also #50)
- [x] ~~descriptions - add more options to contact - whatsapp, wechat, telegram etc.~~
- [ ] descriptions - add more contact types
- [ ] descriptions - add rating (like stars)
- [ ] descriptions - reception opening hours
- [ ] descriptions - deposit/payment options
- [ ] descriptions - GPS location on a room level
- [ ] inventory, descriptions - check in, check out information
- [x] ~~pricing - long-term discounts (for example percentages)~~
- [x] ~~pricing - short-term discounts and specials (for example percentages)~~
- [ ] pricing - different price based on when you pay
- [ ] pricing - breakfast (and other services) included in price
- [ ] pricing - refine modifiers (pets, allergies...)
- [x] ~~pricing - multiple rate plan resolution strategies (right now we do always pick the cheapest) (https://github.com/windingtree/wt-pricing-algorithms/commit/8424c083b6e8f6eede0dd1e9d042e8f41f20d9bf)~~
- [ ] pricing - Add more RatePlanModifier resolution strategies controlled by the property owner - after all, there are modifiers that might raise the price for legitimate reasons (for example pets)
- [ ] pricing - [Occupancy based pricing](https://myallocator.cloudbeds.com/hc/en-us/articles/205672368-Expedia-Pricing-Models-Everything-you-need-to-know)
- [ ] pricing - bookingThreshold
- [ ] pricing - no show fees
- [ ] pricing - Consider pricing models not built around a price per night per person per room.
- [ ] pricing - "Grouping" of rate plans based on dates (`availableForTravel` and `availableForReservation` would essentially become lists of ranges)
- [ ] pricing, availability - we now have days, we might want hours or minutes (including cancellation policy, etc)
- [ ] availability - refine restrictions (arrival, departure, ...)
- [ ] availability - without room numbers, we cannot track particular rooms for consecutive periods of time (see https://github.com/windingtree/wt-write-api/issues/10#issuecomment-407379501)
- [ ] availability performance - implement an efficient mechanism for partial updates (see windingtree/wiki#55 comments)
- [ ] booking - billing information
- [ ] booking - guarantee/deposit information
- [x] booking - information on reseller - windingtree/wt-booking-api#15, windingtree/wt-booking-api#16
- [ ] pricing/booking - different guests might arrive and depart at different times and that might affect the resulting price
- [ ] rate plans/booking - **taxes**
- [ ] description/booking - Terms and conditions
